spring:
  profiles:
    active: dev
  task:
    scheduling:
      pool:
        size: 5
ru:
  homyakin:
    telegram:
      bot:
        admin-id: 210753724
        token: "stab"
        username: "stab"
        channel: "@goodgame_monitoring"

logging.level:
  ru.homyakin: debug